# Generated by Django 4.0.4 on 2022-09-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_postmodel_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='poster',
            new_name='post',
        ),
    ]
